default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'fno'

  #Distributed computing
  distributed:
    use_distributed: False

  # FNO related
  fno:
    data_channels: 1
    n_modes: [64,64]
    hidden_channels: 64
    projection_channels: 256
    n_layers: 4
    domain_padding: 0 #0.078125
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: None
    skip: 'linear'
    implementation: 'reconstructed'
    positional_embedding: 'grid'
    use_channel_mlp: 1
    channel_mlp_expansion: 0.5
    channel_mlp_dropout: 0

    separable: False
    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False
    fno_block_precision: 'full' # or 'half', 'mixed'
    stabilizer: None # or 'tanh'

  # Optimizer
  opt:
    n_epochs: 500
    checkpointing: False
    profiling: False
    resume_from_dir: "./ckpts"
    save_dir: "./ckpts"
    save_every: 1
    learning_rate: 3e-4
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False
    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 50 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 100
    gamma: 0.5
    per_layer_opt: False
    galore: True
    galore_scale: 1.0
    galore_rank: [1.0] # change this within scripts
    galore_warm_restart: True
    act_checkpoint: False # change in later experiments
    naive_galore: False # change this within scripts
    first_dim_rollup: 1 # change this within scripts
    adamw_support_complex: True
    update_proj_gap: 50
    galore_proj_type: left


  # Dataset related
  data:
    root: /global/homes/d/dhpitt/psc/data/navier_stokes
    batch_size: 8
    n_train: 10000
    train_resolution: 128
    n_tests: [2000]
    test_resolutions: [128]
    test_batch_sizes: [8]
    encode_input: True
    encode_output: True
    download: True

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: False
  
  # Weights and biases
  wandb:
    log: True
    name: "" # If None, config will be used but you can override it here
    group: None
    project: "tensorgalore" 
    entity: "pino-training" # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1
    resume: "allow"
  